MobHealth:
  Pig: -1
  Cow: -1
  Spider: -1
  CaveSpider: -1
  Zombie: -1
  Skeleton: -1
  Creeper: -1
  Ocelot: -1
  Bat: -1
  Chicken: -1
  Mooshroom: -1
  Sheep: -1
  Squid: -1
  Villager: -1
  Enderman: -1
  Wolf: -1
  ZombiePigman: -1
  Blaze: -1
  CaveSpider: -1
  Ghast: -1
  MagmaCube: -1
  Silverfish: -1
  Slime: -1
  Witch: -1
  WitherSkeleton: -1
  ZombieVillager: -1
  IronGolem: -1
MobDamage:
  Pig: -1
  Cow: -1
  Spider: -1
  CaveSpider: -1
  Zombie: -1
  Skeleton: -1
  Creeper: -1
  Ocelot: -1
  Bat: -1
  Chicken: -1
  Mooshroom: -1
  Sheep: -1
  Squid: -1
  Villager: -1
  Enderman: -1
  Wolf: -1
  ZombiePigman: -1
  Blaze: -1
  CaveSpider: -1
  Ghast: -1
  MagmaCube: -1
  Silverfish: -1
  Slime: -1
  Witch: -1
  WitherSkeleton: -1
  ZombieVillager: -1
  IronGolem: -1